### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by bgruening** [conda-forge/rdkit-feedstock#10]
The version number does not follow and standard, can we change this to be in sync with the rest and also with the rdkit conda channel?

**Comment by pstjohn** [comment]
The versions here just correspond to the github tags on [rdkit/rdkit](https://github.com/rdkit/rdkit). I'm not sure we'd want to deviate from that, there's some conda-forge stuff that happens to monitor for new tags, etc. But maybe @greglandrum might be willing to change the way releases are tagged upstream.

**Comment by greglandrum** [comment]
What form would you like us to use?

**Comment by pstjohn** [comment]
They might be referring to the labels on the [conda-forge](https://anaconda.org/conda-forge/rdkit) and [rdkit](https://anaconda.org/rdkit/rdkit) channels being different?

**Comment by bgruening** [comment]
`2017.09.3.0` would be nice. `Release_` should not be in the version number.

**Comment by greglandrum** [comment]
`Release` isn't ever in the version number itself, it just shows up in the tags.
Are you using some restriction that the github tag should match the version number?

**Comment by mcs07** [comment]
What about something like this:

```
{% set version = "2017.09.3" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}
{% set sha256 = "6a4d9e9eb0ca06cbcdc20505f0c6ea0b1167b4dcdf7d1185871ba16ce701a5f4" %}

package:
  name: rdkit
  version: {{ version }}

source:
  fn:  {{ filename }}
  url: https://github.com/rdkit/rdkit/archive/{{ filename }}
  sha256: {{ sha256 }}
```
